### PR TITLE
fix(lib): default size for content loader viewbox

### PR DESCRIPTION
**Pull request by nileshbhagwat**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/content-loader/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/ngneat/content-loader/issues/72

## What is the new behavior?

Adding default value for "viewBox" input (previous default value of width and height)

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Thanks. But based on what you decide the default value?

**Comment by nileshbhagwat** [comment]
In v6, input width and height is replaced with the input "viewBox". Default values taken from those previous input to keep it consistent 

image
 
Any suggestion?

**Comment by NetanelBasal** [comment]
Can you please check the original React library?

**Comment by nileshbhagwat** [comment]
Hi @NetanelBasal,  

React version has hardcoded viewbox `0 0 340 84` for custom content loader
https://github.com/danilowoz/react-content-loader/blob/master/src/web/presets/CodeStyle.tsx

Also, OOB loaders have default value for viewbox `0 0 476 124`
https://github.com/ngneat/content-loader/blob/master/projects/ngneat/content-loader/src/lib/facebook-loader.component.ts

Can we consider adding default value for custom content loader as well instead `0 0 0 0` ?

FYI, we are using old version `4.0.0`. this change would be helpful to avoid inconsistency with library upgrade.

**Comment by NetanelBasal** [comment]
Sure you can create a PR, but mark it as breaking change in the commit, please.

**Comment by nileshbhagwat** [comment]
Done, commit updated with breaking change description

**Pull request merged**
