### PR TITLE
Added option to ignore baseUrl for supporting url changes

### PR DESCRIPTION
**Pull request by doronsever**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X ] The commit message follows our guidelines: https://github.com/ngneat/content-loader/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

In our application, we have URLs that change via GET params after the user enters the page.
For some reason, it caused this functionality not work.
I have found out that by removing the URL and just making the baseUrl to be empty, everything works as expected.

Issue Number: N/A

## What is the new behavior?
Added option to ignore baseUrl so the URL at the end will be `#ID` instead of `/RELATIVE_URL#ID`

I also upgraded some packages to remove vulnerabilities 

## Does this PR introduce a breaking change?

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Update the docs, please.

**Comment by doronsever** [comment]
@NetanelBasal do you want me just to change the `changelog.md` file or do you have another way of doing so?

**Comment by NetanelBasal** [comment]
The README file

**Comment by doronsever** [comment]
Done

**Comment by doronsever** [comment]
@NetanelBasal please also upgrade the npm package so we can start using it

**Comment by NetanelBasal** [comment]
Done.

**Pull request merged**
